### ISSUE TITLE
offer to idiom-ize

### ISSUE THREAD

**Issue by ryanckulp** [blockstack/blockstack-ruby#2]
@larrysalibra i'd like to solve https://github.com/blockstack/blockstack-ruby/issues/1, but first let's follow the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide).

```bash
$ cd blockstack-ruby
$ rubocop
$ 10 files inspected, 540 offenses detected
```

happy to contribute [immaterial] styling improvements, then dive into JWT, if appropriate.

standing by.

**Comment by larrysalibra** [comment]
Oh awesome @ryanckulp ! Sorry, I missed this.

Great idea to use the ruby style guide. Can't believe I haven't run into `rubocop` before! Seems great! Thanks so much for the offer! Let's do it!

**Comment by larrysalibra** [comment]
Thanks again @ryanckulp for the pull request.
