### ISSUE TITLE
Blockstack API defaults to localhost:6270

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-ruby#5]
Currently, `Blockstack.api` defaults to `localhost:6270`. I think this only appropriate for Blockstack development, because otherwise `verify_auth_response` will try to validate a domain via the localhost API. When verifying a 'real' Blockstack user, that domain will be missing in the local registrar.

Setting `Blockstack.api = 'https://api.blockstack.org'` resolves this issue.

I can make this change, but I just want to make sure I'm not missing something here.

@larrysalibra

**Comment by larrysalibra** [comment]
Thanks @hstove ! Previously we shipped a node on macOS, so this setting also made sense there too. I fixed this while fixing another issue a user reported on the forum. Defaults to https://core.blockstack.org in the current release.
